name: Refresh Feed
on: [push]
jobs:
  refresh-feed:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch API Data 📦
        uses: gautemo/fetch-api-data-action@1.0.2
        with:
          url: 'https://servicebus2.caixa.gov.br/portaldeloterias/api/megasena/'
          file: './data.json'