name: Refresh Feed
on: [push]
jobs:
  refresh-feed:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch API Data 📦
        uses: JamesIves/fetch-api-data-action@v2
        with:
          endpoint: http://servicebus2.caixa.gov.br/portaldeloterias/api/megasena/
          configuration: '{ "method": "GET" }'