name: Refresh Feed
on: [push]
jobs:
  refresh-feed:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch API Data 📦
        uses: gautemo/fetch-api-data-action@1.0.2
        with:
          url: 'https://registro.br/v2/ajax/whois/?qr=fdfdkjsfvsdafjasdafnbko.com.br'
          file: 'j.json'